default: &DEFAULT
  adapter: sqlite3
  pool: 5

development:
  <<: *DEFAULT
  database: db/me_spring_dev.sqlite3

test:
  <<: *DEFAULT
  database: db/me_spring_test.sqlite3

staging:
  <<: *DEFAULT
  database: db/me_spring_stage.sqlite3

production:
  <<: *DEFAULT
  database: db/me_spring_live.sqlite3
